name: Trigger MyBinder
# This Workflow was adapted from the official docs:
# https://github.com/cranmer/stats-ds-book/blob/master/.github/workflows/merged.yml

on:
  push:
    branches: source

  workflow_dispatch:
  repository_dispatch:

jobs:
  binder:
    name: Trigger Binder build
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Trigger Binder build
      run: bash .github/workflows/trigger_mybinder.sh https://gke.mybinder.org/build/gh/ELC/python-security/source
